# Site settings
title: 西安外国语大学会计ACCA2001班丁玉婕出轨情况说明11_1
author:
  name: papothh76129
description: ""

# Build settings
remote_theme: jekyll/minima
highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
